### ISSUE TITLE
Something wrong when loading .fbx from mixamo

### ISSUE THREAD

**Issue by wyysf-98** [stefanonuvoli/skinmixer#1]
Hi, thanks for your great work. I just built and installed the project, but something went wrong when loading the .fbx file from mixamo.

Attempting to add QLayout "" to SkinMixerManager "SkinMixerManager" which already has a layout.

<img width="685" alt="Snipaste_2022-12-30_03-17-08" src="https://user-images.githubusercontent.com/31622768/210002247-72bd73db-bb8f-49cc-974d-6962bfca49a8.png">

Do you have any suggestion? Looking forward to your reply, THX!!!

**Comment by stefanonuvoli** [comment]
Hi wyysf,

That error is not really related to loading the model, but it is just a Qt error that I never solved because it was not creating any actual problem.

You receive an error when loading an FBX because you didn't install or configure FBXSDK. In the code you can find a #ifndef FBXSDK that will skip FBX loading if the library is not found. This is because I did not want my collaborators to install that library, since I created my own format (rig) to save the data I needed in a more readable way. You solve it by installing FBXSDK and then inserting the right path in configuration.pri. 

Anyways, obviously this project is a prototype and does not handle all the FBX formats, and could raise errors when loading some FBX. However, I never had problems with mixamo FBXs, since they are really high quality.

I apologize for not writing a README with the steps for installation, but I am not mantaining it since I changed my job and I don't work anymore in research. I'm planning to do it whenever I find some spare time.

If you need any help, or need some custom data (.rig, my format), you can write me at stefano.nuvoli@gmail.com.

Regards,
Stefano Nuvoli

**Comment by wyysf-98** [comment]
Hi, Thanks for your quick reply, which really helps me a lot :) 

Yes, I noticed that I have to configure the FBXSKD and installed it from the website: https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2020-2-1

Actually, the error occurred when loading the mixamo FBXs, which is kind of weird. Luckily, I found it works when loading some other files from truebones. Lacking README does not affect me a lot, I didn't have much trouble compiling this project using Ubuntu.

Thanks again for your quick response, it is indeed interesting and great work. Hoping to see more of your work in the future.

Best,
Weiyu

**Comment by stefanonuvoli** [comment]
Hi Weiyu,

Just notice that installing the library is not enough, you have also to set the path in configuration.pri file.

Well, I'm sure that there is a FBX format of Mixamo that work properly with the project. Maybe you have to select the right format when downloading the file. Now it's been a long time, so I don't remember, but definitely there should be a FBX textual format that works properly.

Regards,
Stefano
